from __future__ import annotations

from typing import Protocol


class PVPMDriver(Protocol):
    """Common interface every connector driver must satisfy."""

    def detect(self) -> dict: ...

    def list_ports(self) -> list[dict]: ...

    def connect(self, port: str) -> dict: ...

    def disconnect(self) -> None: ...

    def is_transfer_mode(self) -> bool: ...

    def fetch_device_info(self) -> dict: ...

    def fetch_measurements(self) -> list[dict]: ...
